---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    droplets:
      - { name: development, group: dev }

  tasks:
    - name: Provision DigitalOcean droplet
      digital_ocean_droplet:
        state: "absent" # "absent"
        name: "{{ item.name }}"
        # private_networking: no
        size: "{{ item.size | default('s-1vcpu-1gb') }}"
        image: "{{ item.image | default('centos-7-x64') }}"
        region: "{{ item.region | default('tor1') }}"
        project: "ap-bot-ru-20230206"
        ssh_keys: "{{ item.ssh_keys | default(['37545237']) }}"
        unique_name: yes
      register: created_droplets
      with_items: "{{ droplets }}"

    - name: Add DigitalOcean hosts to inventory groups
      add_host:
        name: "{{ item.1.data.droplet.networks.v4 | selectattr('type','eq','public') | map(attribute='ip_address') | first }}"
        groups: "do,{{ droplets[item.0].group }},{{ item.1.data.droplet.name }}"
        # You can dynamically add inventory variables per-host.
        ansible_user: root
      when: item.1.data is defined
      with_indexed_items: "{{ created_droplets.results }}"

- hosts: do
  remote_user: root
  gather_facts: false

  tasks:
    - name: Wait for hosts to become reachable.
      wait_for_connection:
